version: "3.7"
services:
  punch:
    image: nghdavid/punch:latest
    container_name: punch
    ports:
        - "3000:3000"
    env_file:
        - .env # path to your .env file
    restart: always
    environment:
      - TZ=Asia/Taipei